### ISSUE TITLE
java.lang.ClassNotFoundException: io.ebean.bean.EntityBean

### ISSUE THREAD

**Issue by EnterTG** [caoli5288/SimpleORM#4]
```

1. package Main;
2. 
3. 
4. import org.bukkit.plugin.java.JavaPlugin;
5. 
6. import com.avaje.ebean.EbeanServer;
7. import com.mengcraft.simpleorm.EbeanHandler;
8. import com.mengcraft.simpleorm.EbeanManager;
9. 
10. 
11. public class Core extends JavaPlugin{
12. 
13. 	EbeanServer server;
14. 	
15. 	@SuppressWarnings({ "deprecation" })
16. 	@Override
17. 	public void onEnable()
18. 	{
19. 		EbeanManager manager = getServer().getServicesManager()
20. 				.getRegistration(EbeanManager.class)
21. 				.getProvider();
22. 		EbeanHandler handler = manager.getHandler(this);
23. 		
24. 		if (!handler.isInitialized()) {
25. 			handler.define(Guild.class);
26. 			try {
27. 				handler.initialize();
28. 			} catch(Exception e) {
29. 			}
30. 		}
31. 		handler.reflect();
32. 		handler.install();
33. 		server = handler.getServer();
34. 		
35. 		
36. 		testGuild();
37. 		
38. 	}
39. 	
40. 	
41. 	public void testGuild() 
42. 	{
43. 		Guild g = new Guild();
44. 		server.save(g);
45. 	}
46. }
47. 

1. package Main;
2. 
3. import javax.persistence.Entity;
4. import javax.persistence.Id;
5. import javax.persistence.Table;
6. 
7. @Entity
8. @Table(name = "Guilds")
9. public class Guild {
10. 
11. @Id
12. private int guildId;
13. 
14. private String guildName;
15. 
16. /**
17. * @return the guildId
18. */
19. public int getGuildId() {
20. return guildId;
21. }
22. 
23. /**
24. * @param guildId the guildId to set
25. */
26. public void setGuildId(int guildId) {
27. this.guildId = guildId;
28. }
29. 
30. /**
31. * @return the guildName
32. */
33. public String getGuildName() {
34. return guildName;
35. }
36. 
37. /**
38. * @param guildName the guildName to set
39. */
40. public void setGuildName(String guildName) {
41. this.guildName = guildName;
42. }
43. 
44. 
45. }
46. 
```
```

21:24:44 [ERROR] Error occurred while enabling Guilds v0.1 (Is it up to date?)
21:24:44 java.lang.NoClassDefFoundError: io/ebean/bean/EntityBean
21:24:44 at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_144]
21:24:44 at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_144]
21:24:44 at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_144]
21:24:44 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:131) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
21:24:44 at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:202) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
21:24:44 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
21:24:44 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
21:24:44 at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_144]
21:24:44 at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_144]
21:24:44 at Main.Core.onEnable(Core.java:25) ~[?:?]
21:24:44 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
21:24:44 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
21:24:44 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
21:24:44 at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
21:24:44 at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
21:24:44 at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:439) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
21:24:44 at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
21:24:44 at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:764) [spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
21:24:44 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
21:24:44 Caused by: java.lang.ClassNotFoundException: io.ebean.bean.EntityBean
21:24:44 at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_144]
21:24:44 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
21:24:44 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.3.jar:git-Spigot-5e4e7f3-2349feb]
21:24:44 at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_144]
21:24:44 at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_144]
```

**Comment by caoli5288** [comment]
Seems class conflict with other plugins.

EnterTG <notifications@github.com> 于 2019年7月21日周日 03:25写道：

**Comment by EnterTG** [comment]
I have only installed my plugin and SimpleORM-1.2

**Comment by EnterTG** [comment]
Ok i fixed it somehow.
