### ISSUE TITLE
梦梦,有个关于Redis的问题

### ISSUE THREAD

**Issue by sumdream** [caoli5288/SimpleORM#7]
梦梦你好,我在使用redisWrapper的遇到一个的问题,就是我插件能顺利编译,但是在运行的时候出现了java.lang.NoSuchMethodError.
下面是我的代码
```
    public void addWorld(String worldName) {
        redisWrapper.open(redis -> {
            String s = redis.clientInfo();
            Log.console(s);
            redis.sadd(RedisKeyEnums.getFormatKey(RedisKeyEnums.BC_SERVER_WORLDS, this.serverName), worldName);
        });
    }
```
下面是我控制台的输出
```
[00:19:46] [Server thread/INFO]: [SumBcSuite] id=35 addr=127.0.0.1:55603 laddr=127.0.0.1:6379 fd=7 name= age=16 idle=0 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=26 qbuf-free=20448 argv-mem=10 multi-mem=0 rbs=1024 rbp=4 obl=0 oll=0 omem=0 tot-mem=22298 events=r cmd=client|info user=default redir=-1 resp=2
[00:19:46] [Server thread/WARN]: [SumBcSuite] Task #64 for SumBcSuite v1.0.0 generated an exception
java.lang.NoSuchMethodError: redis.clients.jedis.Jedis.sadd(Ljava/lang/String;[Ljava/lang/String;)J
        at net.sumcraft.spigot.managers.BcServerInfoMgr.lambda$addWorld$1(BcServerInfoMgr.java:131) ~[?:?]
        at com.mengcraft.simpleorm.RedisWrapper.open(RedisWrapper.java:112) ~[?:?]
        at net.sumcraft.spigot.managers.BcServerInfoMgr.addWorld(BcServerInfoMgr.java:128) ~[?:?]
        at net.sumcraft.spigot.managers.BcServerInfoMgr.loadWorlds(BcServerInfoMgr.java:168) ~[?:?]
        at net.sumcraft.spigot.listeners.ServerInfoListener$1.run(ServerInfoListener.java:78) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-8d58cdb8]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421) [CraftScheduler.class:git-CatServer-1.12.2-8d58cdb8]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:900) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]

```
下面是SimpleORM加载的控制台输出
```
[00:19:08] [Server thread/INFO]: [SimpleORM] Loading SimpleORM v1.9.0-SNAPSHOT
[00:19:08] [Server thread/INFO]: Load MavenLibs(javax/persistence/persistence-api/1.0)
[00:19:08] [Server thread/INFO]: Load MavenLibs(org/avaje/ebean/2.8.1)
[00:19:08] [Server thread/INFO]: Load MavenLibs(org/slf4j/slf4j-api/1.7.30)
[00:19:08] [Server thread/INFO]: Load MavenLibs(com/zaxxer/HikariCP/4.0.3)
[00:19:08] [Server thread/INFO]: Load MavenLibs(org/apache/commons/commons-pool2/2.11.1)
[00:19:08] [Server thread/INFO]: Load MavenLibs(redis/clients/jedis/3.8.0)
[00:19:08] [Server thread/INFO]: [SimpleORM] ORM lib load okay!

```
在服务器启动的插件加载的时候redis也能ping,然后返回pong,
这是完整日志,[https://pastebin.com/WaDJUamf](https://pastebin.com/WaDJUamf)

**Comment by sumdream** [comment]
我刚刚把Jedis文件的路径输出了下，发现和SimpleORM项目里面的版本是一致的
```
[09:11:20] [Server thread/INFO]: [SumBcSuite] 开始载入数据库
[09:11:21] [Server thread/ERROR]: ebean.properties not found
[09:11:21] [Server thread/INFO]: Ambiguous ClassLoader choice preferContext:true Context:org.bukkit.plugin.java.PluginClassLoader Caller:org.bukkit.plugin.java.PluginClassLoader
[09:11:21] [Server thread/INFO]: DatabasePlatform name:SumBcSuite@b085688d-5ea5-4e0f-8367-812f643fd871 platform:mysql
[09:11:21] [Server thread/INFO]: Ambiguous ClassLoader choice preferContext:true Context:org.bukkit.plugin.java.PluginClassLoader Caller:org.bukkit.plugin.java.PluginClassLoader
[09:11:21] [Server thread/INFO]: Ambigous ClassLoader (Context vs Caller) chosen org.bukkit.plugin.java.PluginClassLoader@13e2cdee
[09:11:21] [Server thread/INFO]: SubClassFactory parent ClassLoader [org.bukkit.plugin.java.PluginClassLoader]
[09:11:21] [Server thread/INFO]: Ambiguous ClassLoader choice preferContext:true Context:org.bukkit.plugin.java.PluginClassLoader Caller:org.bukkit.plugin.java.PluginClassLoader
[09:11:21] [Server thread/INFO]: ResourceManager initialised: type[file] [plugins/SumBcSuite]
[09:11:21] [Server thread/INFO]: Ambiguous ClassLoader choice preferContext:true Context:org.bukkit.plugin.java.PluginClassLoader Caller:org.bukkit.plugin.java.PluginClassLoader
[09:11:21] [Server thread/INFO]: trimming off 'is' from boolean field name isPublic in class net.sumcraft.spigot.entities.Warp
[09:11:22] [Server thread/ERROR]: Bean property net.sumcraft.spigot.entities.Warp.isPublic has  missing readMethod  missing writeMethod . Should it be transient?
[09:11:22] [Server thread/INFO]: Entities enhanced[0] subclassed[1]
[09:11:22] [Server thread/WARN]: [SumBcSuite] 注入失败了，1.12服务端不再支持注入方式
[09:11:23] [Server thread/INFO]: [SumBcSuite] Tables already exists!
[09:11:23] [Server thread/INFO]: [SumBcSuite] 数据库载入成功
[09:11:23] [Server thread/INFO]: [SumBcSuite] Redis Ping: PONG
[09:11:23] [Server thread/INFO]: [SumBcSuite] file:/root/.m2/repository/redis/clients/jedis/3.8.0/jedis-3.8.0.jar!/redis/clients/jedis/
[09:11:23] [Server thread/INFO]: [SumBcSuite] redis\clients\jedis
[09:11:23] [Server thread/ERROR]: Error occurred while enabling SumBcSuite v1.0.0 (Is it up to date?)
java.lang.NoSuchMethodError: redis.clients.jedis.Jedis.sadd(Ljava/lang/String;[Ljava/lang/String;)J
        at net.sumcraft.SumBcSuiteSpigot.lambda$onEnable$0(SumBcSuiteSpigot.java:68) ~[?:?]
        at com.mengcraft.simpleorm.RedisWrapper.open(RedisWrapper.java:112) ~[?:?]
        at net.sumcraft.SumBcSuiteSpigot.onEnable(SumBcSuiteSpigot.java:61) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-8d58cdb8]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-8d58cdb8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-8d58cdb8]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:438) [CraftServer.class:git-CatServer-1.12.2-8d58cdb8]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384) [CraftServer.class:git-CatServer-1.12.2-8d58cdb8]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:383) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:330) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]

```
代码部分
```
    @Override
    public void onEnable() {
        inst = this;
        cfg = new Config();
        redisWrapper = ORM.globalRedisWrapper();
        teleportMgr = new TeleportMgr();
        bcServerInfoMgr = new BcServerInfoMgr();
        serverNameListener = new ServerInfoListener();
        registerDataBase();
        registerListeners();
        registerChannel();
        registerCommands();
        redisWrapper.open(redis -> {
            String ping = redis.ping();
            Log.console("&bRedis Ping: &c" + ping);
            String path = redis.getClass().getResource("").getPath();
            Log.console(path);
            String replace = redis.getClass().getPackage().getName().replace(".", "\\");
            Log.console(replace);
            redis.sadd("test", "world1","world2");
        });
    }
```

**Comment by caoli5288** [comment]
嗯，，由于jedis作者喜欢瞎几把改方法签名这类的报错其实挺多，从报错看，你代码里调用的是`long sadd(String, String...)`这个方法，然而在`jedis-3.8.0`里这个方法是`Long sadd(String, String...)`

你需要修改你的pom确保编译时引用的是`jedis-3.8.0`

**Comment by sumdream** [comment]
谢谢,原来如此.我把bc插件和spigot写一起了,然后我bc插件上的是jedis4.2.3. 这签名瞎几把改可太刑了
